import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/header";
import ThemeButton from "./components/themeButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      {/* 1. Tell the browser that this page supports dark mode natively. 
          This turns the scrollbars and browser chrome dark immediately. */}
      <meta name="color-scheme" content="light dark" />

        {/* 2. CRITICAL CSS: Set the background color based on SYSTEM settings instantly.
            This effectively eliminates the "White" flash. */}
        <style>{`
          @media (prefers-color-scheme: light) {
            :root {
              background-color: #E5D9C3; /* Your Beige Light Color */
              color: #26201E;
            }
          }
          @media (prefers-color-scheme: dark) {
            :root {
              background-color: #08080E; /* Your Amethyst Dark Color */
              color: #bbc8f2;
            }
          }
        `}</style>
        <Script dangerouslySetInnerHTML={{
          __html: `
            (function() {
                try {
                  // 1. Define the colors in JS so they are available instantly
                  var colors = {
                    light: { bg: '#E5D9C3', fg: '#26201E' },
                    dark: { bg: '#08080E', fg: '#bbc8f2' }
                  };

                  // 2. Determine the user's preference
                  var theme = localStorage.getItem('theme');
                  var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  
                  var mode = 'light'; // default variable
                  if (theme === 'dark' || (!theme && systemDark)) {
                    mode = 'dark';
                  }

                  // 3. APPLY IMMEDIATELY (The Core Fix)
                  // We set the class for Tailwind...
                  document.documentElement.classList.add(mode);
                  
                  // ...AND we manually paint the background variable to prevent the flash
                  document.documentElement.style.setProperty('--background', colors[mode].bg);
                  document.documentElement.style.setProperty('--foreground', colors[mode].fg);
                  
                  // Helper: Tell the browser UI (scrollbars, etc) to match
                  document.documentElement.style.colorScheme = mode;

                } catch (e) {}
              })();
          `,
        }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
      <Header />
      <main className="grow">
        {children}
      </main>
        

        <Footer />
        <div className="theme-button hidden md:block fixed bottom-8 right-8 z-40">
          <ThemeButton/>
        </div>
      </body>
    </html>
  );
}
